# workflow name
name: Generate release-artifacts

# on events
on:
  release:
    types:
      - created

jobs:
  ci:
    name: "Run CI"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup go version 1.13
        uses: actions/setup-go@v3
        with:
          go-version: 1.13
      - run: go version
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
          platforms: "linux/amd64, darwin/amd64, windows/amd64"
          name: "389ds_exporter"
          compress: "true"
          dest: ".build"
