name: "CI"
on: ["push", "pull_request"]
jobs:
  ci:
    name: "Run CI"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup go version 1.13
        uses: actions/setup-go@v3
        with:
          go-version: 1.13
      - run: go version

      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1"
